set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR ppc)

set(AMIGAOS4_SDK "$ENV{AMIGAOS4_SDK}" CACHE PATH "AmigaOS 4 SDK root")
if(NOT AMIGAOS4_SDK)
    message(FATAL_ERROR "AMIGAOS4_SDK must point to the AmigaOS 4 SDK")
endif()

set(CMAKE_C_COMPILER "${AMIGAOS4_SDK}/bin/ppc-amigaos-gcc")
set(CMAKE_CXX_COMPILER "${AMIGAOS4_SDK}/bin/ppc-amigaos-g++")
set(CMAKE_AR "${AMIGAOS4_SDK}/bin/ppc-amigaos-ar")
set(CMAKE_RANLIB "${AMIGAOS4_SDK}/bin/ppc-amigaos-ranlib")

set(CMAKE_FIND_ROOT_PATH
    "${AMIGAOS4_SDK}"
    "${AMIGAOS4_SDK}/local"
)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_EXE_LINKER_FLAGS_INIT "-use-dynld")
